-- Пустая таблица без реального назначения в приложении: даёт GitHub Actions
-- workflow (.github/workflows/keep-alive.yml) что-то реально запросить в
-- БД, чтобы Supabase не приостанавливал проект по неактивности (see
-- https://supabase.com/docs/guides/platform/free-project-pausing — пауза
-- считается по запросам к БД, а не по вызовам Edge Functions).
create table if not exists public.keep_alive (
  id bigint generated by default as identity primary key
);

insert into public.keep_alive default values;

alter table public.keep_alive enable row level security;

create policy "keep_alive_select_anon" on public.keep_alive
  for select
  to anon
  using (true);
